### ISSUE TITLE
[Service request] Salesforce

### ISSUE THREAD

**Issue by gokaygurcan** [inket/stts#140]
Hi,

Heroku is in the list, and a part of the bigger Salesforce products, but it'd be nice if we also have Salesforce Core, B2C/Marketing/Sales/other clouds, Mulesoft, etc. 

It's not as straightforward as Heroku, since these products spread across multiple locations and instances, and each instance has their own audience (customers/partners/etc).

Here's the general status page for Salesforce products: https://trust.salesforce.com/en/
And here's an example for B2C Cloud: https://status.salesforce.com/instances/ODS-US01
I'm not sure if this changes anything but they also have an api: https://api.status.salesforce.com/v1/docs/

I know it's not a clear request, maybe we an shape it together. 

Cheers,
G.

**Comment by inket** [comment]
Thanks for telling me about this!

I think the Salesforce products can be added easily, but for the ones in https://status.salesforce.com/current, what do you think about having them divided by regions? Just like Azure:

<img width="288" alt="Screen Shot 2021-07-11 at 4 37 25 PM" src="https://user-images.githubusercontent.com/679224/125186649-95a39780-e266-11eb-894c-ad2d9062c528.png">

 Any more precise (like by instance) would be unmanageable since that would make the lists in the app too long.

**Comment by gokaygurcan** [comment]
Hi again,

Yea, I guess region is also good in terms of division. In the end, instances are split into regions, and anyone in Europe shouldn't care about an instance in North America anyway :P I think that might work.

Thanks for considering this.

**Comment by inket** [comment]
Added in #141 👍 Should be released this week.

<img width="328" alt="Screen Shot 2021-08-15 at 6 02 19 PM" src="https://user-images.githubusercontent.com/679224/129473131-7cb20812-a9e1-4fff-b118-6294b215a6e5.png">

**Comment by gokaygurcan** [comment]
Thanks a lot 🚀
